//TAG_NEW_ASSET

TU_MACRO_ASSETTYPE(tu::CAsset_Image, m_ImagesCatalog, "Image", "Image")
TU_MACRO_ASSETTYPE(tu::CAsset_Sprite, m_SpritesCatalog, "Sprite", "Sprite")
TU_MACRO_ASSETTYPE(tu::CAsset_Skeleton, m_SkeletonsCatalog, "Skeleton", "Skeleton")
TU_MACRO_ASSETTYPE(tu::CAsset_SkeletonSkin, m_SkeletonSkinsCatalog, "Skeleton skin", "SkeletonSkin")
TU_MACRO_ASSETTYPE(tu::CAsset_SkeletonAnimation, m_SkeletonAnimationsCatalog, "Skeleton animation", "SkeletonAnim")
TU_MACRO_ASSETTYPE(tu::CAsset_Character, m_CharactersCatalog, "Character", "Character")
TU_MACRO_ASSETTYPE(tu::CAsset_CharacterPart, m_CharacterPartsCatalog, "Character part", "Characterpart")
TU_MACRO_ASSETTYPE(tu::CAsset_Weapon, m_WeaponsCatalog, "Weapon", "Weapon")
TU_MACRO_ASSETTYPE(tu::CAsset_Map, m_MapsCatalog, "Map", "Map")
TU_MACRO_ASSETTYPE(tu::CAsset_MapGroup, m_MapGroupsCatalog, "Group", "Group")
TU_MACRO_ASSETTYPE(tu::CAsset_MapZoneTiles, m_MapZoneTilesCatalog, "Tiled zone", "Tiledzone")
TU_MACRO_ASSETTYPE(tu::CAsset_MapLayerTiles, m_MapLayerTilesCatalog, "Tiled layer", "TilesLayer")
TU_MACRO_ASSETTYPE(tu::CAsset_MapLayerQuads, m_MapLayerQuadsCatalog, "Quads layer", "QuadsLayer")
TU_MACRO_ASSETTYPE(tu::CAsset_ZoneType, m_ZoneTypesCatalog, "Zone type", "ZoneType")
TU_MACRO_ASSETTYPE(tu::CAsset_GuiRectStyle, m_GuiRectStylesCatalog, "Rectangle style", "RectStyle")
